# Generated by Django 5.2.1 on 2025-06-02 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='password',
        ),
        migrations.AddField(
            model_name='contestant',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contestant',
            name='phone',
            field=models.CharField(default=78966, max_length=20, validators=[django.core.validators.RegexValidator(regex='^(\\+7|8)?[\\s\\-]?\\(?\\d{3}\\)?[\\s\\-]?\\d{3}[\\s\\-]?\\d{2}[\\s\\-]?\\d{2}$')]),
            preserve_default=False,
        ),
    ]
